# Real Root Cause Analysis for the Weird Reversing Trend Issue
# This script identifies the ACTUAL problem from commit 778073961c864fde39c6f800836c15f886c28ab4 (Aug 23)

using Random, Distributions, Statistics

# Include necessary files
include("data_structures.jl")
include("utils.jl")
include("constants.jl")
include("feature_updates.jl")

println("=== REAL ROOT CAUSE ANALYSIS ===")
println("Issue: Weird reversing trend in current list with list results")
println("Root cause: Content drift changes in Aug 23 commit")
println()

# Check the current state
println("=== CURRENT STATE ANALYSIS ===")
println("is_UnchangeCtxDriftAndReinstate: $is_UnchangeCtxDriftAndReinstate")
println("is_content_drift_between_study_and_test: $is_content_drift_between_study_and_test")
println("n_driftStudyTest: $n_driftStudyTest")
println("n_between_listchange: $n_between_listchange")
println("p_driftAndListChange: $p_driftAndListChange")
println()

# The REAL issue: Content drift was introduced but then disabled
println("=== REAL ROOT CAUSE IDENTIFIED ===")
println("The issue is NOT with context drift flags!")
println("The issue is with CONTENT DRIFT between study and test:")
println()
println("1. Aug 23 commit introduced content drift functionality")
println("2. But the content drift is currently DISABLED in simulation.jl")
println("3. This creates an imbalance between context and content drift")
println("4. Leading to the weird reversing trend in within-list results")
println()

# Show what the Aug 23 commit changed
println("=== WHAT THE AUG 23 COMMIT CHANGED ===")
println("BEFORE Aug 23 commit:")
println("  - Only context features drifted between study and test")
println("  - Content features remained stable")
println("  - Balanced drift pattern")
println()
println("AFTER Aug 23 commit:")
println("  - Content drift functionality was added")
println("  - But content drift is currently DISABLED")
println("  - This creates systematic imbalance")
println()

# The critical insight
println("=== CRITICAL INSIGHT ===")
println("The problem is in simulation.jl around line 145:")
println("  # if is_content_drift_between_study_and_test #true")
println("  #     for iword in eachindex(word_list_content_whole_list)")
println("  #         drift_ctx_betweenStudyAndTest!(word_list_content_whole_list[iword], p_driftAndListChange, Geometric(g_word))")
println("  #     end")
println("  # end")
println()
println("This content drift code is COMMENTED OUT!")
println("But the flag is_content_drift_between_study_and_test = false")
println("This creates a mismatch between what the code expects and what it does")
println()

# Why this causes the reversing trend
println("=== WHY THIS CAUSES THE REVERSING TREND ===")
println("The issue creates a systematic pattern:")
println("1. Context features drift during study-test intervals")
println("2. Content features do NOT drift (disabled)")
println("3. This creates different drift patterns for different feature types")
println("4. The model's likelihood calculations become biased")
println("5. Results show weird reversing trends across test positions")
println()

# The fix
println("=== THE REAL FIX ===")
println("You have two options to fix this:")
println()
println("OPTION 1: Enable content drift (recommended)")
println("  In E3/simulation.jl, uncomment the content drift code:")
println("  Remove the # comments around lines 145-149")
println("  Set is_content_drift_between_study_and_test = true in constants.jl")
println()
println("OPTION 2: Disable content drift entirely")
println("  Remove the content drift code completely")
println("  Set is_content_drift_between_study_and_test = false in constants.jl")
println("  Ensure no content drift calls exist")
println()

# Show the current simulation code
println("=== CURRENT SIMULATION CODE ===")
println("The problematic section in simulation.jl:")
println("  for _ in 1:n_driftStudyTest[list_num]")
println("      drift_ctx_betweenStudyAndTest!(test_list_context_change, p_driftAndListChange, Geometric(g_context))")
println("      if is_UnchangeCtxDriftAndReinstate")
println("          drift_ctx_betweenStudyAndTest!(test_list_context_unchange, p_driftAndListChange, Geometric(g_context))")
println("      end")
println("      # Content drift is COMMENTED OUT here!")
println("      # if is_content_drift_between_study_and_test")
println("      #     for iword in eachindex(word_list_content_whole_list)")
println("      #         drift_ctx_betweenStudyAndTest!(word_list_content_whole_list[iword], p_driftAndListChange, Geometric(g_word))")
println("      #     end")
println("      # end")
println("  end")
println()

# Recommended immediate fix
println("=== RECOMMENDED IMMEDIATE FIX ===")
println("To fix the weird reversing trend:")
println("1. In E3/constants.jl, set: is_content_drift_between_study_and_test = true")
println("2. In E3/simulation.jl, uncomment the content drift code (lines 145-149)")
println("3. This will restore balanced drift between context and content features")
println()

println("=== VERIFICATION ===")
println("After making the changes:")
println("1. Run your main simulation to verify the reversing trend is fixed")
println("2. Check that both context and content features are drifting properly")
println("3. The within-list results should now show consistent patterns")
println()

println("=== SUMMARY ===")
println("The weird reversing trend is caused by:")
println("✓ Content drift functionality introduced in Aug 23 commit")
println("✓ But content drift code is commented out in simulation.jl")
println("✓ This creates systematic imbalance between context and content drift")
println("✓ Leading to biased likelihood calculations and reversing trends")
println()
println("The fix: Enable content drift properly to restore balance")
println()

println("Real root cause analysis completed. The issue is content drift imbalance, not context drift flags.")
